export const TOGGLE_SIDEBAR = Symbol('TOGGLE_SIDEBAR')
export const SHOW_PRELOADER = Symbol('SHOW_PRELOADER')
export const HIDE_PRELOADER = Symbol('HIDE_PRELOADER')
export const SHOW_DIALOG = Symbol('SHOW_DIALOG')
export const CLOSE_DIALOG = Symbol('CLOSE_DIALOG')
export const SHOW_SNACKBAR = Symbol('SHOW_SNACKBAR')
export const SHOW_HTTP_ERROR_DIALOG = Symbol('SHOW_HTTP_ERROR_DIALOG')
export const CLOSE_HTTP_ERROR_DIALOG = Symbol('CLOSE_HTTP_ERROR_DIALOG')

export const LOG_IN = Symbol('LOG_IN')

export const FETCH_SERIALS = Symbol('FETCH_SERIALS')
export const FETCH_SERIALS_DONE = Symbol('FETCH_SERIALS_DONE')
export const FETCH_SERIAL = Symbol('FETCH_SERIAL')
export const FETCH_SERIAL_DONE = Symbol('FETCH_SERIAL_DONE')
export const CREATE_SERIAL = Symbol('CREATE_SERIAL')
export const CREATE_SERIAL_DONE = Symbol('CREATE_SERIAL_DONE')
export const UPDATE_SERIAL = Symbol('UPDATE_SERIAL')
export const UPDATE_SERIAL_DONE = Symbol('UPDATE_SERIAL_DONE')
export const REMOVE_SERIAL = Symbol('REMOVE_SERIAL')
export const REMOVE_SERIAL_DONE = Symbol('REMOVE_SERIAL_DONE')

export const FETCH_COUNTRIES = Symbol('FETCH_COUNTRIES')
export const FETCH_COUNTRIES_DONE = Symbol('FETCH_COUNTRIES_DONE')
export const CREATE_COUNTRY = Symbol('CREATE_COUNTRY')
export const CREATE_COUNTRY_DONE = Symbol('CREATE_COUNTRY_DONE')

export const FETCH_DIRECTORS = Symbol('FETCH_DIRECTORS')
export const FETCH_DIRECTORS_DONE = Symbol('FETCH_DIRECTORS_DONE')
export const CREATE_DIRECTOR = Symbol('CREATE_DIRECTOR')
export const CREATE_DIRECTOR_DONE = Symbol('CREATE_DIRECTOR_DONE')
export const REMOVE_DIRECTOR = Symbol('REMOVE_DIRECTOR')
export const REMOVE_DIRECTOR_DONE = Symbol('REMOVE_DIRECTOR_DONE')

export const FETCH_STUDIOS = Symbol('FETCH_STUDIOS')
export const FETCH_STUDIOS_DONE = Symbol('FETCH_STUDIOS_DONE')
export const CREATE_STUDIO = Symbol('CREATE_STUDIO')
export const CREATE_STUDIO_DONE = Symbol('CREATE_STUDIO_DONE')
export const REMOVE_STUDIO = Symbol('REMOVE_STUDIO')
export const REMOVE_STUDIO_DONE = Symbol('REMOVE_STUDIO_DONE')

export const REMOVE_IMAGE = Symbol('REMOVE_IMAGE')
export const REMOVE_IMAGE_DONE = Symbol('REMOVE_IMAGE_DONE')

export const FETCH_SEASONS = Symbol('FETCH_SEASONS')
export const FETCH_SEASONS_DONE = Symbol('FETCH_SEASONS_DONE')
export const FETCH_SEASON = Symbol('FETCH_SEASON')
export const FETCH_SEASON_DONE = Symbol('FETCH_SEASON_DONE')
export const CREATE_SEASON = Symbol('CREATE_SEASON')
export const CREATE_SEASON_DONE = Symbol('CREATE_SEASON_DONE')
export const UPDATE_SEASON = Symbol('UPDATE_SEASON')
export const UPDATE_SEASON_DONE = Symbol('UPDATE_SEASON_DONE')
