export const TOGGLE_SIDEBAR = Symbol('TOGGLE_SIDEBAR')
export const SHOW_PRELOADER = Symbol('SHOW_PRELOADER')
export const HIDE_PRELOADER = Symbol('HIDE_PRELOADER')

export const LOG_IN = Symbol('LOG_IN')

export const FETCH_SERIALS = Symbol('FETCH_SERIALS')
export const FETCH_SERIALS_DONE = Symbol('FETCH_SERIALS_DONE')
export const FETCH_SERIAL = Symbol('FETCH_SERIAL')
export const FETCH_SERIAL_DONE = Symbol('FETCH_SERIAL_DONE')

export const FETCH_COUNTRIES = Symbol('FETCH_COUNTRIES')
export const FETCH_COUNTRIES_DONE = Symbol('FETCH_COUNTRIES_DONE')

export const FETCH_DIRECTORS = Symbol('FETCH_DIRECTORS')
export const FETCH_DIRECTORS_DONE = Symbol('FETCH_DIRECTORS_DONE')
export const CREATE_DIRECTOR = Symbol('CREATE_DIRECTOR')
export const CREATE_DIRECTOR_DONE = Symbol('CREATE_DIRECTOR_DONE')
export const REMOVE_DIRECTOR = Symbol('REMOVE_DIRECTOR')
export const REMOVE_DIRECTOR_DONE = Symbol('REMOVE_DIRECTOR_DONE')

export const FETCH_STUDIOS = Symbol('FETCH_STUDIOS')
export const FETCH_STUDIOS_DONE = Symbol('FETCH_STUDIOS_DONE')
export const CREATE_STUDIO = Symbol('CREATE_STUDIO')
export const CREATE_STUDIO_DONE = Symbol('CREATE_STUDIO_DONE')
